### ISSUE TITLE
Thanks for this - I think HomeState is unnecessary bcoz (HomeState.loggedOut() can fit in to AuthState

### ISSUE THREAD

**Issue by chrisgate** [SimpleBoilerplates/Flutter#20]
Thanks for this Boilerplate ,i am currently using it on app that will soon go to production .

I think HomeState is unnecessary bcoz (HomeState.loggedOut() can fit in to AuthState.

@freezed
class AuthState with _$AuthState {
  const factory AuthState.initial() = _Initial;
  const factory AuthState.loading() = _Loading;
  const factory AuthState.loggedIn() = _LoggedIn;
  const factory AuthState.loggedOut() = _LoggedOut;
  const factory AuthState.error(AppException error) = _Error;
}

Cheers

**Comment by Sadmansamee** [comment]
in current situation it's unnecessary but when you will add more feature on home then it will come handy.
