### ISSUE TITLE
[readme.md] please consider adding usage instructions

### ISSUE THREAD

**Issue by neiljaywarner** [SimpleBoilerplates/Flutter#21]
please consider adding usage instructions, I didn't understand how to use it via mason or whatever and looking at mason didn't really yield useful results, nor very_good_ci's issues

**Comment by neiljaywarner** [comment]
i did find https://github.com/VeryGoodOpenSource/very_good_cli/issues/77#issuecomment-1039679099
but did not yet watch the livestream

**Comment by Sadmansamee** [comment]
@neiljaywarner They provided excellent instructions [here](https://github.com/VeryGoodOpenSource/very_good_cli)

**Comment by neiljaywarner** [comment]
How do I use with your template?
They said mason...
