### ISSUE TITLE
Used template build failed with an exception

### ISSUE THREAD

**Issue by dyardy** [SimpleBoilerplates/Flutter#22]
I am really not sure what is causing this build error, any help would be appreciated.  I have tried any number of combinations but yet no success.  Any ideas?

![bQ3rgMRZ9s](https://user-images.githubusercontent.com/261526/184516428-1d59acf5-3c11-462f-a66c-08287a92bf0a.png)

**Comment by Sadmansamee** [comment]
@dyardy Thanks for pointing out, there was some old config for Android, I fixed in the latest commit, if error still occurs clear your .gradle cache from you home folder.
