### ISSUE TITLE
Feature request for ChangeNotifierProvider

### ISSUE THREAD

**Issue by tahesse** [SimpleBoilerplates/Flutter#25]
This flutter template only shows how to work with `StateNotifierProvider` where the state is a model.
What is an example of when to use `ChangeNotifierProvider` and can we include it in this boilerplate?

I am willing to do a PR here.

**Comment by Sadmansamee** [comment]
I am reluctant to use **ChangeNotifierProvider**, currently I am changing `StateNotifierProvider` to newly introduced `NotifierProvider`.

**Comment by Sadmansamee** [comment]
`StateProvider`, `StateNotifierProvider`, `ChangeNotifierProvider`. These are legacy and shouldn't be used anymore.
