### ISSUE TITLE
Unable to make playstore build .aab file

### ISSUE THREAD

**Issue by visha12345** [SimpleBoilerplates/Flutter#27]
Flutter Biolerplate project

Tried using different commands:
flutter build appbundle --release --flavor production -t lib/main_production.dart
flutter build appbundle  --flavor production -t lib/main_production.dart

but Playstore showing
You uploaded an APK or Android App Bundle that was signed in debug mode. You need to sign your APK or Android App Bundle in release mode.

Also 
//    buildTypes {
//        release {
//            signingConfig signingConfigs.release
//            minifyEnabled true
//            useProguard true
//            proguardFiles getDefaultProguardFile('proguard-android.txt')
//        }
//        debug {
//            signingConfig signingConfigs.debug
//        }
//    }

giving issue when project built.

Need solution, with which i can have playstore build ready asap.

**Comment by Sadmansamee** [comment]
Change this line
```
signingConfig signingConfigs.debug
```
to 
```
signingConfig signingConfigs.release
```
