### ISSUE TITLE
flutter pub get doesn't work

### ISSUE THREAD

**Issue by Alexakis97** [SimpleBoilerplates/Flutter#6]
> [flutter-boilerpplate] flutter pub get
> Running "flutter pub get" in flutter-boilerpplate...            
> Because boilerplate depends on intl ^0.17.0 which doesn't match any versions, version solving failed.
> pub get failed (1; Because boilerplate depends on intl ^0.17.0 which doesn't match any versions, version solving failed.)
> exit code 1

```
dependency_overrides:
  intl: any
```

solved it with the above dependency but can we have an updated version of the boilerplate on v2?

```

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Warning
──────────────────────────────────────────────────────────────────────────────
Your Flutter application is created using an older version of the Android
embedding. It's being deprecated in favor of Android embedding v2. Follow the
steps at

https://flutter.dev/go/android-project-migration

to migrate your project.
```

**Comment by Sadmansamee** [comment]
@Alexakis97 Better For localization better install this [plugin](https://plugins.jetbrains.com/plugin/13666-flutter-intl)
and you should also take a merge with latest update with the repo's master branch, it has lots of updates including migrating **AndroidX**, **Android embedding v2**
